# Generated by Django 5.1.7 on 2025-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('governorate', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Sfax', 'Sfax'), ('Gabès', 'Gabès'), ('Medenine', 'Medenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kebili', 'Kebili')], default='Tunis', max_length=100)),
            ],
        ),
    ]
