version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: db_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yosra
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:Yosra@db:5432/db_django

volumes:
  postgres_data: