# Generated by Django 5.1.7 on 2025-04-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_identification',
        ),
    ]
