# Generated by Django 5.1.7 on 2025-05-08 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_invoice_billing_address_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
