# Generated by Django 5.1.7 on 2025-05-08 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_alter_invoiceitem_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
