# Generated by Django 5.1.7 on 2025-05-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_alter_invoiceitem_unit_price_ht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
    ]
