# Generated by Django 5.1.7 on 2025-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_remove_invoiceitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
