# Generated by Django 5.1.7 on 2025-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
