# Generated by Django 5.1.7 on 2025-05-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validite', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
