# Generated by Django 5.1.7 on 2025-04-30 03:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Bon de Livraison',
                'verbose_name_plural': 'Bons de Livraison',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
