# Generated by Django 5.1.7 on 2025-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('Vendu', 'Vendu'), ('Retour', 'Retour'), ('Endommagé', 'Endommagé'), ('Ajustement', 'Ajustement d’inventaire'), ('Prélèvement', 'Prélèvement'), ('Réapprovisionnement', 'Réapprovisionnement')], max_length=50),
        ),
    ]
