# Generated by Django 5.1.7 on 2025-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mvt', '0003_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('Vendu', 'Vendu'), ('Retour', 'Retour'), ('Endommagé', 'Endommagé'), ('Prélèvement', 'Prélèvement'), ('Réapprovisionnement', 'Réapprovisionnement')], max_length=50),
        ),
    ]
