# Generated by Django 5.1.7 on 2025-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mvt', '0005_stockmovement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('SOLD', 'Vendu'), ('RETURN', 'Retour'), ('DAMAGED', 'Endommagé'), ('WITHDRAWAL', 'Prélèvement'), ('RESTOCK', 'Réapprovisionnement')], max_length=50),
        ),
    ]
