# Generated by Django 5.1.7 on 2025-05-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '__first__'),
        ('customers', '__first__'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNCONFIRMED', 'Commande non confirmée'), ('CONFIRMED', 'Commande confirmée'), ('STOCK_VERIFICATION', 'Vérification du stock'), ('PREPARATION', 'Préparation de la commande'), ('PACKAGING', 'Emballage de la commande'), ('WAITING_FOR_PAYMENT', 'En attente de paiement'), ('PAYMENT_ERROR', 'Erreur de paiement'), ('PAID', 'Payée'), ('SHIPPED', 'Commande expédiée'), ('DELIVERED_PAID', 'Commande livrée et payée'), ('CANCELLED', 'Annulée'), ('RETURNED', 'Retournée')], default='UNCONFIRMED', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces '), ('CARD', 'Carte bancaire')], default='CASH', max_length=20)),
                ('stock_preleve', models.BooleanField(default=False)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Retrait en magasin'), ('DELIVERY', 'Livraison à domicile')], default='DELIVERY', max_length=20)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='addresses.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='addresses.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
