# Generated by Django 5.1.7 on 2025-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Commande non confirmée'), ('CONFIRMED', 'Commande confirmée'), ('STOCK_VERIFICATION', 'Vérification du stock'), ('PREPARATION', 'Préparation de la commande'), ('PACKAGING', 'Emballage de la commande'), ('WAITING_FOR_PAYMENT', 'En attente de paiement'), ('PAYMENT_ERROR', 'Erreur de paiement'), ('PAID', 'Payée'), ('SHIPPED', 'Commande expédiée'), ('DELIVERED_PAID', 'Commande livrée et payée'), ('CANCELLED', 'Annulée'), ('RETURNED', 'Retournée')], default='UNCONFIRMED', max_length=20),
        ),
    ]
