# Generated by Django 5.1.7 on 2025-04-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces '), ('CARD', 'Carte bancaire')], default='CASH', max_length=20),
        ),
    ]
