# Generated by Django 5.1.7 on 2025-03-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
