# Generated by Django 5.1.7 on 2025-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_preleve',
            field=models.BooleanField(default=False),
        ),
    ]
