# Generated by Django 5.1.7 on 2025-03-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
