# Generated by Django 5.1.7 on 2025-03-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_notification_order_notification_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
