# Generated by Django 5.1.7 on 2025-05-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('Liter', 'liter'), ('Meter', 'meter')], default='kg', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Coût d'achat")),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix de vente unitaire')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA (%)')),
                ('include_vat', models.BooleanField(default=False, verbose_name='Toutes taxes comprises (TTC)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('STOCK_ADD', 'Ajout stock'), ('STOCK_REMOVE', 'Retrait stock')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
