# Generated by Django 5.1.7 on 2025-04-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('Liter', 'liter'), ('Meter', 'meter')], default='kg', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Coût d'achat")),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix de vente unitaire')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA (%)')),
                ('include_vat', models.BooleanField(default=False, verbose_name='Toutes taxes comprises (TTC)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
            ],
        ),
    ]
