# Generated by Django 5.1.7 on 2025-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='include_vat',
            field=models.BooleanField(default=False, verbose_name='Toutes taxes comprises (TTC)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name="Coût d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix de vente unitaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA (%)'),
        ),
    ]
