# Generated by Django 5.1.7 on 2025-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
